### ISSUE TITLE
アーカイブ配信の手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#11]
参考: https://github.com/insidefrontend/issue-1/issues/6#issuecomment-283293419

**Comment by RyotaSugawara** [comment]
結局有料イベントでの生配信はするんでしたっけ？
しないとしたら、セッションの録画をお願いする形で、後日一般公開という形ですね。

**Comment by ahomu** [comment]
あー、そっか！そういう議論もあった。録画かも。

**Comment by RyotaSugawara** [comment]
あと配信方法はYouTubeとかですかね〜
+YouTubeチャンネルの準備とかもしておきます

**Comment by ahomu** [comment]
ちょっと、運営タスク多すぎなので、社内に他の担当作った方が良い気がしてきてます。ぼちぼち。

**Comment by RyotaSugawara** [comment]
今回ライブ配信はせず、後日一般公開
撮影についてはセミナールームに機材が導入することになるとのことなので、そちらを使う可能性あり（確認中）
後日使用方法のレクチャーをしていただく予定

**Comment by ahomu** [comment]
@RyotaSugawara これって機材はセミナールームに導入されたものが利用可能ってことで大丈夫なんですっけ？ 運用スタッフはどれくらい必要？

**Comment by RyotaSugawara** [comment]
機材ですが、上西くんの手配で3台カメラを借りて、SDに録画する形になります。
予備として録画用に私物の一眼レフも持っていく予定。
（別途SDカード購入は必要）

以前業者にお願いしたときもスタッフは各セッションに付きON/OFF押す係が必要だったみたいなので、各部屋に1名ずつ配置する予定です。

**Comment by ahomu** [comment]
もろもろ承知しました！ 司会とあわせて、配置図に追加お願いします。

**Comment by hiloki** [comment]
ちなみに `ライブ` ではないよね？今回。

**Comment by RyotaSugawara** [comment]
> ちなみに ライブ ではないよね？今回。

はい、ライブではなく録画を後日配信という形でアーカイブをYouTubeに上げます。

**Comment by sakit0** [comment]
youtubeあげたら閉じる？

**Comment by RyotaSugawara** [comment]
編集時間かかりそうなので5月末までにアップロードする目安のスケジュール感
セミナー / AMAは別動画？

https://www.youtube.com/channel/UCIXvE12FNUi9sPkoUWqIXtQ
