### ISSUE TITLE
会場掲示物の手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#13]

**Comment by hiloki** [comment]
必要そうなもの:
- [x] 部屋ごとの掲示
  - 開催中のセッションタイトル
  - AMAのsli.do URL
- [x] 控室エリアの立ち入り禁止
- ~トイレ案内~
- [x] 控室張り紙
- [x] 1Fの会場案内
  - イベント名
  - フロア
  - 時間
  - 連絡先

**Comment by hiloki** [comment]
Finally done!
