### ISSUE TITLE
入館手続き、会場設備、利用ルール確認

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#18]
飲食、電源、Wifi、喫煙、トイレ、緊急時対応 etc

```
- 会場の飲食ルール？
- 喫煙場は屋外？
    - 外にでる場合、ゲストが滞在中の入退館はどうなる？
- 土曜日、エントランスの正面を開放したい（要申請＆交渉）
- 急病人が出たときなどの緊急時連絡先
    - ビルの管理室？ 緊急車両の誘導などの都合、ビルをとおした方が良い場合あるはず
- Wifi は LILO 使えるよねきっと
    - 休日は止まってるとかないよね...
```

**Comment by ahomu** [comment]
https://docs.google.com/presentation/d/14haZEIm-KVPGehFX4npw-bCrOl3-RBbjtRu2iHqlcnc/edit#slide=id.p に当日案内スライド（よくあるループでぐるぐる回すやつ）にまとめる

**Comment by ahomu** [comment]
@hiloki  ☝️当日用案内スライドの体裁を整えるの後からお願いすること発生する（カモ）

**Comment by sakit0** [comment]
今年使ったやつ
https://docs.google.com/presentation/d/e/2PACX-1vS60FafOOR4mdf1TVb01nH62zvsfEEHtqvTEUx57Rdt14SDtKVWwkyVyOpv-5rrEAKmcvX9r99Hl659/pub?start=false&loop=true&delayms=5000
