### ISSUE TITLE
運営ロードマップ

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#2]
- 1月
  - タイムテーブル草案作成
  - Webサイトを2019年版に更新
  - CFP内容摺り合わせ
- 2月
  - CFP募集開始(2月中旬)
    - 〆切: 3月中旬
    - 発表: 3月末
- 3月
  - 海外ゲストFIX〆切
  - CFP発表
  - タイムテーブル更新
  - ↑同時期に一般募集開始
    - Peatix: 2000 ~ 3000yen
      - connpassの流入もほしいのでconnpassからもPeatixに流す
    - 先着順: 300くらい
    - 期間は前日ギリギリくらいまで？
  - スカラシップ周り動き出し
- 4月
  - 国内ゲストFIX〆切
  - 運営設備確認(4中〜5頭くらい)
  - 予算FIX?
- 5月
  - 18日 当日

**Comment by sakit0** [comment]
お疲れ様でしたぁあああああああああ
