### ISSUE TITLE
スタッフの当日配置図と人数の概算

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#20]

**Comment by 7110** [comment]
@ahomu @RyotaSugawara （ @sakito21, @basara669 
お疲れ様です！ヤフーの内藤です

ヤフー側のスタッフ募集を始めようと思うのですが、
当日のスタッフ人数の概算について確認しておきたく、
配置と人数はどんな感じでしょうか？

**Comment by sakit0** [comment]
無事終わり
