### ISSUE TITLE
Peatix 開設（有料チケット販売）

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-3#23]

**Comment by RyotaSugawara** [comment]
Peatix有料チケットメモ
---
- 販売手数料：4.9% + 99円/チケット1枚 + 210円（振込手数料）
  - https://about.peatix.com/pricing.html#pricing

- [払い出し情報の登録方法](https://help.peatix.com/customer/ja/portal/articles/2766394-%E6%89%95%E3%81%84%E5%87%BA%E3%81%97%E6%83%85%E5%A0%B1%E3%81%AE%E7%99%BB%E9%8C%B2%E6%96%B9%E6%B3%95)
  - 払い出し情報（銀行口座情報）のご登録は、イベント公開後に設定が可能

**Comment by ahomu** [comment]
済み
