### ISSUE TITLE
司会台本の作成

### ISSUE THREAD

**Issue by sakit0** [insidefrontend/issue-3#28]
gistにでも作る

**Comment by sakit0** [comment]
## 14:50の最初のセッションのみ開始挨拶
みなさま、本日はinside frontendにお越しいただきまして誠にありがとうございます。
本日セッションルーム〇〇の司会進行を務めさせていただきます、〇〇株式会社の〇〇と申します。
よろしくお願い致します。

## 毎セッション開始前
この部屋はセッションRoom-○になります。
続いて行われるセッションは、「○○(セッション名)になります」。

モニターに会場案内図、wifi、ハッシュタグを表示しています。
セッション開始まで、いましばらくお待ちください。

## セッション案内
お待たせいたしました。ただいまより「〇〇(セッション名)」をはじめさせていただきます。
〇〇株式会社 〇〇様です、それではよろしくお願い致します。

## セッション終了後の案内
〇〇様、ありがとうございました。
只今より、AMAの準備を開始致します。
休憩のためにルームDを設けております。休憩される方はそちらをご利用ください。
そのほかに今回スポンサー頂いている企業様の展示も行なっております、ぜひお立ち寄りください。

それでは少々お待ちください。

## AMA開始
それではAMAをはじめさせていただきます。
今回は、sli.doというサービスを使用し、質問をしていただきたいと思います。
画面に表示されているQRコードを読み取り、質問を投稿してください。

(質問入れている時間があるので自己紹介はあと)
申し遅れました、今回AMAの進行を務めさせていただきます、〇〇株式会社の〇〇と申します。
よろしくお願い致します。
(ここからはアドリブ？)

## AMA終了
〇〇様、セッション、AMAありがとうございました。（拍手）
ここで〇〇分まで休憩時間とさせていただきます、次のセッションまでお待ちください。

## 全セッション終了のアナウンス
これをもちまして、本日のすべてのセッションを終了させて頂きます。
このあと、自由参加の懇親会があります、こちらは参加費無料ですの是非ご参加ください。

懇親会の準備を致しますので、最後にこちらのアンケート(画面に写す)にご協力ください。

**Comment by sakit0** [comment]
これでよければなにかしら見やすい形にして共有する

**Comment by st44100** [comment]
> (ここからはアドリブ？)

アドリブ・・・

**Comment by sakit0** [comment]
無事おわり
