### ISSUE TITLE
英 → 日字幕用翻訳

### ISSUE THREAD

**Issue by studiomohawk** [insidefrontend/issue-3#29]
## 前提

- 字幕はAndrew Betts氏作の http://triblondon.github.io/subtrack/ を利用
- `subtrack` はPublicなGoogle Sheetを読んで字幕を表示
- Google SheetはAndrew提供のモノと同じフォーマットで作成する
- B列 OR C列の日本語が表示される。B列は機械翻訳した結果が表示されている

動作の例: Andrew提供のトークスクリプトを利用して表示するには?

- http://triblondon.github.io/subtrack/ を Chrome で開く
- Spreadsheet URL に `https://docs.google.com/spreadsheets/d/1hveN4S6PdHlvaKI2wkCCX1YFF74eXDBgNIQ5z_0B708/edit#gid=0` を入力
- Load button を onClick

ちなみに:

- slides are left and right arrows, captions are A and S keys.  Q to toggle captions on and off

![こんな具合で表示されます via 谷](https://user-images.githubusercontent.com/28534/57663525-4a15e480-762f-11e9-92a7-882e7b1c6650.png)

## TypeScript: Why and how we adopted it at Slack by Felix Rieseberg

@basara669 さん担当

https://docs.google.com/spreadsheets/d/1sSQP7gZ-xwdg-3QDMWc88VRBNxnPnQ5XI8hehof7BGc/edit#gid=0

## Introduction to Lucet by Adam Foltzer

@Tetsuya3850

& @studiomohawk → Doing クラシックに下から翻訳してます。

https://docs.google.com/spreadsheets/d/1-_NEyzrE4AthP70iwV_RotdRWkaVS-B8PGJ2a4QYxWo/edit#gid=0

## Making less of the web with feature policy by Andrew Betts

@studiomohawk → Done

https://docs.google.com/spreadsheets/d/1hveN4S6PdHlvaKI2wkCCX1YFF74eXDBgNIQ5z_0B708/edit#gid=0

**Comment by basara669** [comment]
@studiomohawk 
とりあえずこれが来たら、これをやればいいですか？？

> TypeScript: Why and how we adopted it at Slack by Felix Rieseberg

**Comment by studiomohawk** [comment]
@basara669 

そうですね。明日には来ます!

**Comment by studiomohawk** [comment]
埋まったのでDone!
ありがとうございました。
